/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  sidebar: [
    "index",
    "introduction",
    {
      Install: [
        "install/index",
        "install/autorest-versioning",
        "install/installing-via-nvm",
        "install/installing-via-nvs",
      ],
    },
    {
      "Create OpenAPI Definition for Autorest": [
        {
          type: "doc",
          id: "openapi/index",
          label: "Overview",
        },
        ,
        "openapi/formats",
        "openapi/request-body",
        "openapi/prechecker",
        {
          "How-to Guides": [
            "openapi/howto/$ref-siblings",
            "openapi/howto/archboard_feedback",
            "openapi/howto/binary-payload",
            "openapi/howto/polymorphism",
          ],
        },
      ],
    },
    {
      "Generate Clients with AutoRest": [
        {
          type: "doc",
          id: "generate/index",
          label: "Overview",
        },
        "generate/how-autorest-generates-code-from-openapi",
        "generate/flags",
        "generate/authentication",
        "generate/built-in-directives",
        "generate/directives",
        {
          Examples: [
            "generate/examples/basic",
            "generate/examples/tags",
            {
              Multilanguage: [
                "generate/examples/multilanguage/index",
                "generate/examples/multilanguage/readme.java",
                "generate/examples/multilanguage/readme.python",
              ],
            },
          ],
        },
      ],
    },
    "client",
    {
      "End-User Documentation": [
        {
          type: "doc",
          id: "user/index",
          label: "Overview",
        },
        "user/command-line-interface",
        "user/configuration",
        {
          "Literate File Formats": [
            "user/literate-file-formats/index",
            "user/literate-file-formats/configuration",
            "user/literate-file-formats/openapi",
          ],
        },
      ],
    },
    "migrate",
    {
      "Develop with AutoRest": [
        {
          type: "doc",
          id: "developer/index",
          label: "Overview",
        },
        "developer/conventions",
        "developer/feature-status-tracking",
        "developer/writing-an-extension",
      ],
    },
    {
      type: "link",
      label: "Powershell Documentation",
      href: "https://github.com/Azure/autorest.powershell/blob/master/docs/readme.md",
    },
    {
      Extensions: [
        "extensions/index",
        {
          Examples: [
            "extensions/swagger-extensions-examples/x-ms-code-generation-settings",
            "extensions/swagger-extensions-examples/x-ms-discriminator-value",
          ],
        },
      ],
    },
    "docker",
    "troubleshooting",
    "faq",
    {
      "Release Notes": [
        {
          type: "doc",
          label: "Overview",
          id: "releases/index",
        },
        "releases/july-2021",
        "releases/july-2022",
        "releases/march-2022",
        "releases/november-2021",
        "releases/september-2021",
      ],
    },

    // { type: "autogenerated", dirName: "generate" },
  ],
};

module.exports = sidebars;
